jobs:
  include:
  - language: node_js
    node_js: node
    env:
    - PORT=port 
    - SECRET_KEY=secret_key 
    - MAIL_HOST=mail_host 
    - MAIL_PORT=mail_port 
    - MAIL_USER=mail_user
    - MAIL_PASS=mail_pass
    - TYPE=type
    - PRIVATE_KEY_ID=private_key_id
    - PRIVATE_KEY=private_key
    - CLIENT_EMAIL=client_email
    - CLIENT_ID=client_id
    - AUTH_URI=auth_uri
    - TOKEN_URI=token_uri
    - AUTH_PROVIDER_X509_CERT_URL=auth_provider_x509_cert_url
    - CLIENT_X509_CERT_URL=client_x509_cert_url
    - PROJECT_ID=project_id
    before_install:
    - cd api
    before_script:
    - node config-compile.js
